export const messengerEmptyData = {
  searchFieldData: {
    name: 'search',
    type: 'text',
    label: 'Поиск',
    value: '',
    search: true,
    mix: 'field--search messages-board__search',
  },
  chatCardsData: [
    {
      imageHref: 'assets/images/avatar.jpg',
      imageAlt: 'avatar',
      name: 'Андрей',
      text: 'Изображение',
      fulltime: '2020-10-10 10:49',
      time: '10:49',
      unread: 2,
    },
    {
      imageHref: 'assets/images/avatar2.jpg',
      imageAlt: 'avatar',
      name: 'Киноклуб',
      text: '<span>Вы: </span>стикер',
      fulltime: '2020-10-10 12:00',
      time: '12:00',
    },
    {
      imageHref: 'assets/images/avatar3.jpg',
      imageAlt: 'avatar',
      name: 'Илья',
      text: 'Друзья, у меня для вас особенный выпуск новостей!...',
      fulltime: '2020-10-10 15:12',
      time: '15:12',
      unread: 2,
    },
    {
      imageHref: 'assets/images/avatar4.jpg',
      imageAlt: 'avatar',
      name: 'Вадим',
      text: '<span>Вы: </span>Круто!',
      fulltime: '2020-10-11 00:00',
      time: '00:00',
    },
    {
      imageHref: 'assets/images/avatar5.jpg',
      imageAlt: 'avatar',
      name: 'тет-а-теты',
      text: 'И Human Interface Guidelines и Material Design рекомендуют...',
      fulltime: '2020-10-11 00:00',
      time: '00:00',
    },
    {
      imageHref: 'assets/images/avatar6.jpg',
      imageAlt: 'avatar',
      name: '1,2,3',
      text: 'Миллионы россиян ежедневно проводят десятки часов свое...',
      fulltime: '2020-10-11 00:00',
      time: '00:00',
    },
    {
      imageHref: 'assets/images/avatar7.jpg',
      imageAlt: 'avatar',
      name: 'Design Destroyer',
      text: 'В 2008 году художник Jon Rafman  начал собирать...',
      fulltime: '2020-10-11 00:00',
      time: '00:00',
    },
    {
      imageHref: 'assets/images/avatar8.jpg',
      imageAlt: 'avatar',
      name: 'Day.',
      text: 'Так увлёкся работой по курсу, что совсем забыл его анонсир...',
      fulltime: '2020-10-11 00:00',
      time: '00:00',
    },
    {
      imageHref: 'assets/images/avatar9.jpg',
      imageAlt: 'avatar',
      name: 'Стас Рогозин',
      text: 'Можно или сегодня или завтра вечером.',
      fulltime: '2020-10-11 00:00',
      time: '00:00',
    },
    {
      imageHref: 'assets/images/avatar10.jpg',
      imageAlt: 'avatar',
      name: 'Прохвост',
      text: 'Беги, скотина, я тебя найду!',
      fulltime: '2020-10-11 00:00',
      time: '00:00',
    },
    {
      imageHref: 'assets/images/avatar.jpg',
      imageAlt: 'avatar',
      name: 'Андрей',
      text: 'Изображение',
      fulltime: '2020-10-10 10:49',
      time: '10:49',
      unread: 2,
    },
    {
      imageHref: 'assets/images/avatar2.jpg',
      imageAlt: 'avatar',
      name: 'Киноклуб',
      text: '<span>Вы: </span>стикер',
      fulltime: '2020-10-10 12:00',
      time: '12:00',
    },
    {
      imageHref: 'assets/images/avatar3.jpg',
      imageAlt: 'avatar',
      name: 'Илья',
      text: 'Друзья, у меня для вас особенный выпуск новостей!...',
      fulltime: '2020-10-10 15:12',
      time: '15:12',
      unread: 2,
    },
    {
      imageHref: 'assets/images/avatar4.jpg',
      imageAlt: 'avatar',
      name: 'Вадим',
      text: '<span>Вы: </span>Круто!',
      fulltime: '2020-10-11 00:00',
      time: '00:00',
    },
    {
      imageHref: 'assets/images/avatar5.jpg',
      imageAlt: 'avatar',
      name: 'тет-а-теты',
      text: 'И Human Interface Guidelines и Material Design рекомендуют...',
      fulltime: '2020-10-11 00:00',
      time: '00:00',
    },
    {
      imageHref: 'assets/images/avatar6.jpg',
      imageAlt: 'avatar',
      name: '1,2,3',
      text: 'Миллионы россиян ежедневно проводят десятки часов свое...',
      fulltime: '2020-10-11 00:00',
      time: '00:00',
    },
    {
      imageHref: 'assets/images/avatar7.jpg',
      imageAlt: 'avatar',
      name: 'Design Destroyer',
      text: 'В 2008 году художник Jon Rafman  начал собирать...',
      fulltime: '2020-10-11 00:00',
      time: '00:00',
    },
    {
      imageHref: 'assets/images/avatar8.jpg',
      imageAlt: 'avatar',
      name: 'Day.',
      text: 'Так увлёкся работой по курсу, что совсем забыл его анонсир...',
      fulltime: '2020-10-11 00:00',
      time: '00:00',
    },
    {
      imageHref: 'assets/images/avatar9.jpg',
      imageAlt: 'avatar',
      name: 'Стас Рогозин',
      text: 'Можно или сегодня или завтра вечером.',
      fulltime: '2020-10-11 00:00',
      time: '00:00',
    },
    {
      imageHref: 'assets/images/avatar10.jpg',
      imageAlt: 'avatar',
      name: 'Прохвост',
      text: 'Беги, скотина, я тебя найду!',
      fulltime: '2020-10-11 00:00',
      time: '00:00',
    },
  ],
};
